### ISSUE TITLE
Support Categories and Specialicazions in "Get Addons" section

### ISSUE THREAD

**Issue by 3DMakerHub** [jliddev/WowUp#200] opened 2020-10-22 16:04 UTC
It would be nice if we could get a search tab in the "get addons" section that we can search for different addons like espacially for heal or dd. 

Something like in the twitch manager. 
![image](https://user-images.githubusercontent.com/66880793/96899115-cf423180-1490-11eb-91fb-686d3507b061.png)
![image](https://user-images.githubusercontent.com/66880793/96899145-d9fcc680-1490-11eb-87ba-4e06ba6e2fe5.png)
![image](https://user-images.githubusercontent.com/66880793/96899190-e719b580-1490-11eb-9253-8f9fbcae1f64.png)

Appreciate if that would be integrated. So far besides of that i love wowup. 

Best regards
Chris

**Comment by mrchops1024** [comment] 2020-10-22 23:16
Looks like a dupe of #73

**Comment by jliddev** [comment] 2020-10-23 01:32
This is a dupe of #73 and is more in depth that it seems.

**Closed by jliddev** 2020-10-23 01:32 UTC
