### ISSUE TITLE
[feature request] choosing the language. [edit: dupe to #177]

### ISSUE THREAD

**Issue by Barracuda666** [jliddev/WowUp#291] opened 2020-10-31 19:52 UTC
Option to choose to have the application in english no matter the OS locale

**Comment by mrchops1024** [comment] 2020-10-31 20:53
This is definitely something that's on the roadmap.

Duplicate of #177

**Comment by jliddev** [comment] 2020-11-01 17:36
closed as dupe

**Closed by jliddev** 2020-11-01 17:36 UTC
