### ISSUE TITLE
[2.x] Column sort direction from previous session not saved

### ISSUE THREAD

**Issue by panoplybez** [jliddev/WowUp#358] opened 2020-11-07 01:37 UTC
When I'm in wowup My Addons I sort by a specific column as Descending (arrow points down, so newest is as the top), but when I close wowup and launch it again, it remembers which column I had sorted, but changes it to Ascending instead. I tried this on 2 different columns and same behavior, it flips my sort direction on new launch. Would prefer it to persist the direction across sessions.

**Comment by mrchops1024** [comment] 2020-11-07 02:11
Dupe of #316

**Comment by panoplybez** [comment] 2020-11-07 02:17
Ahh sorry, I searched open issues, forgot to search closed ones.

**Closed** 2020-11-07 02:17 UTC
