### ISSUE TITLE
Ability to create Profile to sync addons between different PCs

### ISSUE THREAD

**Issue by Cratis1831** [jliddev/WowUp#101] opened 2020-10-04 14:34 UTC

**Comment by Noxis-source** [comment] 2020-10-04 16:07
I think this is a kind of the same thing?
https://github.com/jliddev/WowUp/issues/20

**Comment by Gorthezar** [comment] 2020-10-10 19:40
Would really like to see this but as far as I'm aware the reason this worked with twitch was cloud-based backups meaning unless there was enough money being made on the project to make cloud servers worth the investment for the dev or coded in some way that you might be able to use google drive as a backup? I know some chrome extensions like RES(Reddit Enhancement Suite) let you save you setting to your own google drive to be redownloaded and reinstalled.

**Comment by RichiCoder1** [comment] 2020-10-17 19:32
@Noxis-source That one is more addon packs then profile sync.

@Gorthezar That's how I'd probably implement this. Offer google/onedrive/box sync as they all have pretty easy to integrate APIs.

**Comment by jliddev** [comment] 2020-10-23 16:26
Duplicate of #20

**Closed by jliddev** 2020-10-23 16:26 UTC
