### ISSUE TITLE
Crashes when trying to search for new addons

### ISSUE THREAD

**Issue by wheatbread** [jliddev/WowUp#129] opened 2020-10-14 07:16 UTC
v1.18.3

When I click on "Get Addons" and then search for anything in the search field, the Wowup client crashes.

**Comment by wahyuen** [comment] 2020-10-14 07:33
might be related to new version....worked this morning when i tried on 1.18.2

**Comment by DaveBurlingame** [comment] 2020-10-14 07:38
Agree with Wheatbread.  Just had the same issue 3 times.  Using the word(s) "bag" and "bags"

**Comment by TopoDiFogna** [comment] 2020-10-14 09:07
[wowup-logs20201014.txt](https://github.com/jliddev/WowUp/files/5376967/wowup-logs20201014.txt)
Logs from the crash.
Opened WoWUp switched to get addons tab and searched :) hope this is useful

**Comment by mkvlrn** [comment] 2020-10-14 10:02
@TopoDiFogna 
>  as a developer myself this can be the right time to check timeouts and network errors?

Do a PR, my man. Code is all there.

**Comment by TopoDiFogna** [comment] 2020-10-14 10:09
Sorry didn't want to sound selfish, apologize for that.
Not a C# developer but I'll take a look this evening when I'll be done
working :)

I appreciate your work, again sorry for that.

Il giorno mer 14 ott 2020 alle ore 12:03 Mike Valeriano <
notifications@github.com> ha scritto:

**Comment by prom3theu5** [comment] 2020-10-14 10:49
its because TukUI appears to be down - the api call crashes the app

**Comment by TopoDiFogna** [comment] 2020-10-14 10:52
Creating a pull request right now 😄

**Comment by prom3theu5** [comment] 2020-10-14 10:54
Beat me to it - literally just forked 👍

**Comment by Arignir** [comment] 2020-10-14 11:00
I can confirm this bug.

> its because TukUI appears to be down - the api call crashes the app

I hope i'll be fix even if TukUI is up again :(

**Comment by jliddev** [comment] 2020-10-14 14:41
This should be fixed in 1.18.4

**Comment by TopoDiFogna** [comment] 2020-10-14 19:38
It's fixed now, we can close this

Thank you

**Closed** 2020-10-23 16:45 UTC
