### ISSUE TITLE
Feature Request: Weak Aura updater

### ISSUE THREAD

**Issue by seathasky** [jliddev/WowUp#188] opened 2020-10-20 14:10 UTC
**Just want to start off by saying, been testing the Alpha client for WoWUp on MacOS and it's working wonderfully! Thanks for your efforts!**
My request is to add support for wago.io. Similar to the WeakAuras companion or better yet this one: https://github.com/AcidWeb/CurseBreaker 

![68747470733a2f2f692e696d6775722e636f6d2f413344483178662e706e67](https://user-images.githubusercontent.com/17598024/96598092-86398400-12bc-11eb-86ef-366e96c13847.png)

I'm almost certain you can scrape from here:  https://data.wago.io 
Not certain though.
This way people have an all in one updater. Tired of using 3 lol! 

Thanks for your consideration!

![Screen Shot 2020-10-20 at 10 14 56 AM](https://user-images.githubusercontent.com/17598024/96598704-242d4e80-12bd-11eb-9ace-07ec59d10aa7.png)

**Comment by seathasky** [comment] 2020-10-21 19:33
Hello. Anyone home?

**Comment by iggy** [comment] 2020-10-21 20:01
> Hello. Anyone home?

I'm not the developer of this project (or even know anything about them), but in general, that's not how open source projects work. They are usually something someone does in their free time. Many times it's something we only do on weekends or when we've got a down night during the week. You should have no expectation that your issue will be looked at in a certain amount of time.

In general, you should only comment on issues when you have something useful to add (i.e. you found another bit of software that does something similar, you figured out what format the data is in, etc). Be patient. Someone will eventually respond to your ticket, it just might take a little while. Especially right now since it looks like this is mostly a one-man show at the moment.

**Comment by seathasky** [comment] 2020-10-21 20:07
As a developer myself I'm trying yo understand where you are coming from, but find it difficult to share the same sentiment as you. Secondly, I never asked for your opinion and really don't need someone telling me what I can of cannot do. I didn't set expectations for this developer to do anything with my suggestion, I was just looking for a reply. You're white knighting the wrong way, I've done nothing wrong here. Move along.

**Comment by jliddev** [comment] 2020-10-21 21:18
Duplicate of #15 we'll get there.

**Closed by jliddev** 2020-10-21 21:18 UTC
