### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Addonman** [jliddev/WowUp#323] opened 2020-11-04 12:46 UTC
Can we have some statistic about addon we DL?Numbers of ppl instaled it for instance.Also it would be nice to have similar window that you get now  in CF-with change log,versions you can DL if last DL is not good and screenshots of addon.

**Comment by jliddev** [comment] 2020-11-05 06:36
The download counts are on the 'Get Addons' page. changelog is a duplicate of #54

**Closed by jliddev** 2020-11-05 06:36 UTC
