### ISSUE TITLE
Selectable addon sources

### ISSUE THREAD

**Issue by grimmtooth** [jliddev/WowUp#121] opened 2020-10-11 14:26 UTC
It would be good to be able to enable / disable sources such as curse, wowinterface, github, tukui.  Right now they are all **on** but it would be good to exclude certain sites. For example, I don't know the veracity of anything on github - for all I know, an addon could be a trojan horse containing something nasty.  So I'd personally be turning off github if I could.

**Comment by jliddev** [comment] 2020-11-05 06:11
Duplicate of #83

**Closed by jliddev** 2020-11-05 06:11 UTC
Labels: enhancement
