### ISSUE TITLE
[Feature Request] Different Colors

### ISSUE THREAD

**Issue by RAtwood90** [jliddev/WowUp#246] opened 2020-10-28 11:10 UTC
Hey WoWUP Developer! Nice Addon Managment System you made Bro! Congratz on that!

It's possible for you to add a different Color Option for the Border and Main Title so my WoW Up can shown up in Blue, Black or White?

Regards Atwood

**Comment by jliddev** [comment] 2020-11-05 06:20
duplicate of #59

**Closed by jliddev** 2020-11-05 06:21 UTC
